# docker build -t predictmod:v0.3.1-frontend -f dockerfile .
FROM predictmod:frontend-base


COPY ./static/ /var/www/html/predictmod/
COPY ./default /etc/nginx/sites-available/default

CMD ["nginx", "-g", "daemon off;"]
