# docker build -t predictmod:v0.3.1-flask -f dockerfile.flask .
FROM python:3.10-slim-buster

COPY . /predictmod

WORKDIR /predictmod/matlab-interface

RUN pip3 install -r requirements.txt

CMD ["gunicorn", "--bind", "0.0.0.0:4243", "wsgi:app"]
