# docker build -t predictmod:v0.3.1-node-tst -f dockerfile.node .
FROM node:18

COPY . /predictmod

EXPOSE 4244

WORKDIR /predictmod

RUN npm install && npm install vite-node

CMD ["npx", "vite-node", "vite_server.js"]
