# docker build -t predictmod:v0.3.1-frontend .
FROM python:3.10-slim-buster

COPY . /server

WORKDIR /server

RUN pip3 install -r requirements.txt

EXPOSE 8000

CMD ["gunicorn", "--bind", "0.0.0.0:4244", "server.wsgi"]
