# docker build -t predictmod:v0.3.1-frontend .
FROM python:3.10-slim-buster


ARG DEBIAN_FRONTEND=noninteractive
RUN mkdir -p /var/log/gunicorn/ && \
    mkdir -p /var/run/gunicorn/ && \
    apt update && \
    apt install -y python3-dev

COPY ./ /server
WORKDIR /server

RUN pip3 install -r requirements.txt

# CMD ["gunicorn", "-c", "gunicorn_conf.py"]
CMD [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
