# docker build -t predictmod:v0.3.1-frontend -f dockerfile .
FROM predictmod:middleware-base

COPY ./ /server
WORKDIR /server

CMD ["gunicorn", "-c", "gunicorn_conf.py"]
# CMD [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
