# Generated by Django 4.1.3 on 2024-07-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PendingModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("version", models.CharField(max_length=24)),
                ("data_type", models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name="ReleasedModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("version", models.CharField(max_length=24)),
                ("release_date", models.DateField()),
                ("data_type", models.CharField(max_length=24)),
                ("model_type", models.CharField(max_length=256)),
                ("data_meta", models.JSONField()),
                ("information_mapping", models.JSONField(null=True)),
                ("additional_details", models.JSONField(null=True)),
                ("backend", models.URLField()),
            ],
        ),
    ]
