# Generated by Django 4.1.3 on 2024-07-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingmodel",
            name="link",
            field=models.URLField(default="/models/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="releasedmodel",
            name="link",
            field=models.URLField(default="/models/"),
            preserve_default=False,
        ),
    ]
