# Generated by Django 5.0.1 on 2025-01-14 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_trainedmodel_siteuser_trained_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteuser",
            name="trained_models",
        ),
        migrations.AddField(
            model_name="trainedmodel",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.siteuser",
            ),
        ),
    ]
