# Generated by Django 5.0.1 on 2025-01-14 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_siteuser_trained_models_trainedmodel_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trainedmodel",
            old_name="user",
            new_name="siteuser",
        ),
    ]
