# docker build -t predictmod:v0.3.1-backend .
FROM python:3.10-slim-buster

COPY . /backend

WORKDIR /backend

RUN pip3 install -r requirements.txt

CMD ["gunicorn", "--bind", "0.0.0.0:4245", "wsgi:app"]
