[conditions]
"Type 2 Diabetes Mellitus" = "Content TBD"

[interventions]
None = """\
The data is from Keser, Toma et al. “Increased plasma N-glycome complexity is associated with \
higher risk of type 2 diabetes.” Diabetologia vol. 60,12 (2017): 2352-2360. \
doi:10.1007/s00125-017-4426-9 and was provided by Dr. Olga Gornik, Faculty of Pharmacy and Biochemistry, University of Zagreb.\
"""

[data_types]
Glycomic = """\
The data is from Keser, Toma et al. “Increased plasma N-glycome complexity is associated with higher risk of type 2 diabetes.” \
Diabetologia vol. 60,12 (2017): 2352-2360. doi:10.1007/s00125-017-4426-9 and was provided by Dr. Olga Gornik, Faculty of \
Pharmacy and Biochemistry, University of Zagreb.\
"""

[infrastructure]
BCO = "BCO_Diabetes_Glycomic.json"
model_type = "Decision Tree Classifier (DTC)"
data_type = "Glycomic"
backend = "PredictMod-KM-Analysis-Backend"
condition = "Type 2 Diabetes Mellitus"
intervention = "None"
input_data_type = "Glycomic"
data_meta = ""
