########### MDClone_Diet_Counseling ###############
[MDClone_Diet_Counseling]
name = "MDClone Diet Counseling"
version = "1.1"
release_date = 2023-12-01
model_type = "Decision Tree Classifier (DTC)"
data_type = "EHR Diet"
backend = "predict-backend"
condition = "Prediabetes"
intervention = "Diet - Dietary Counseling"
input_data_type = "EHR"

[MDClone_Diet_Counseling.data_meta]
Patients = 19842
"Data Features" = 19
#################################################
########### Metagenomic_Exercise ###############
[Metagenomic_Exercise]
name = "MG Exercise"
version = "1.1"
release_date = 2023-05-01
model_type = "Decision Tree Classifier (DTC)"
data_type = "Gut-Microbiome"
backend = "predict-backend"
condition = "Prediabetes"
intervention = "Exercise"
input_data_type = "Gut-Microbiome"

[Metagenomic_Exercise.data_meta]
Patients = 40
Genomes = 281
#################################################

########### Diabetes_EHR ###############
[Diabetes_EHR]
BCO = "Diabetes_EHR_v1/BCO_raw_Diabetes_EHR_Classifier.json"
model_type = "Decision Tree Classifier (DTC)"
data_type = "EHR"
backend = "predict-backend"
condition = "Prediabetes"
intervention = "Exercise"
input_data_type = "EHR-Synthea"

[Diabetes_EHR.data_meta]
#################################################

########### Epilepsy_classifier_1.1 ###############
["Epilepsy_classifier"]
BCO = "Epilepsy_microbiome_v1/BCO_raw_Epilepsy_classifier.json"
# Guessing; BCOs don't contain. Also, is this EHR, metagenomic, etc?
data_type = "Epilepsy EHR"
model_type = "Decision Tree Classifier (DTC)"
backend = "predict-backend"
condition = "Epilepsy"
intervention = "Diet - Keto Diet"
input_data_type = "Gut-Microbiome"

["Epilepsy_classifier".data_meta]
# Taken from README, BCOs should contain this in future
Patients = 500
Features = 188
#################################################

########### Epic_Cosmos_EHR_Keto_1.0 ###############
["PredictMod-EHR-Keto"]
BCO = "PredictMod_EHR_Keto_v1.0/BCO/temp_PEHR.json"
# Unclear from the README; BCO indicates prediabetes as a keyword
data_type = "EHR"
model_type = "Support Vector Machine (SVM)"
backend = "predict-backend"
condition = "Prediabetes"
intervention = "Diet - Keto Diet"
input_data_type = "EHR-Epic-Cosmos"

["PredictMod-EHR-Keto".data_meta]
# Taken from README, BCOs should contain this in future
Patients = 308
Features = 26
#################################################

########### Ovarian_Cancer_Methylation_1.0 ###############
["Ovarian-Cancer-Methylation"]
BCO = "ovarian_cancer_methylation/BCO.json"
# Unclear from the README
data_type = "Methylation"
model_type = "Decision Tree"
backend = "predict-backend"
condition = "Ovarian Cancer (Methylation data)"
# Unclear intervention
intervention = "Observational"
input_data_type = "Methylation profiles"

["Ovarian-Cancer-Methylation".data_meta]
# Again, unclear what features of the data set exist
# Patients = 308
# Features = 26
#################################################

########### Ovarian_Cancer_Methylation_1.0 ###############
["Ovarian-Cancer-RNASeq"]
BCO = "ovarian_rnaseq/BCO.json"
# Unclear from the README
data_type = "RNASeq"
model_type = "Random Forest Classifier"
backend = "predict-backend"
condition = "Ovarian Cancer (RNASeq data)"
# Unclear intervention
intervention = "Observational"
input_data_type = "RNA Seq"

["Ovarian-Cancer-RNASeq".data_meta]
Samples = 29
Features = 17
#################################################
