[conditions]
Prediabetes = """\
A precursor to Type 2 Diabetes Mellitus (T2DM), where blood sugars are higher than normal, \
but not high enough to be considered T2DM. Prediction outcomes are based \
on a 5% reduction in weight, HOMA-IR, or a diagnosis of T2DM."""
Epilepsy = """\
A neurological disorder in which nerve cell activity in the brain \
is disturbed, causing seizures. Prediction outcomes are based on [TBD].
"""
"Renal Carcinoma" = """\
[TBD]
"""
"Type 2 Diabetes Mellitus" = "Content TBD"

[interventions]
[interventions.Prediabetes]
"Diet - Dietary Counseling" = "Involves following a physician-recommended diet for the management of prediabetes."
"Diet - Keto Diet" = "A low-carb, ketogenic diet commonly recommended for the management of prediabetes."
"Exercise" = "Involves following a physician-recommended exercise regimen for the management of prediabetes."
"Medication - Semaglutide" = "Medication management of prediabetes using an increasingly popular GLP1-agonist."
"No Intervention" = "Predictions based on existing biomarkers. These predictions do not involve a specific intervention."

[interventions.Epilepsy]
"Diet - Keto Diet" = "A low-carb, ketogenic diet commonly recommended for the management of prediabetes."

[interventions."Renal Carcinoma"]
None = "[TBD]"

[interventions."Type 2 Diabetes Mellitus"]
None = "[TBD]"

[input_data_types]
[input_data_types.Prediabetes]
"EHR" = "Data sourced from clinical Electronic Health Records, e.g. EPIC-COSMOS or MDClone"
"EHR-Synthea" = "Data sourced from the Synthea synthetic data patient cohort"
"Gut-Microbiome" = "Microflora population and diversity information measured via High Throughput Sequencing"
"Glycoproteomics" = "TBD"
"Glycomics" = "TBD"

[input_data_types.Epilepsy]
"Gut-Microbiome" = """\
Epilepsy data set was provided by Department of Veterians Affairs. This was used as a training set \
to generate a 500 patient dataset for the epilepsy gut microbiome classifier and predictor \
"""

[input_data_types."Type 2 Diabetes Mellitus"]
Glycomic = "[TBD]"

# [url_targets]
# [url_targets.Prediabetes]
# EHR = "MDClone-Diet-Exercise"
# "Gut-Microbiome" = "MG-Exercise"

# [url_targets.Epilepsy]

# [url_targets."Renal Carcinoma"]