
[PredictMod_EHR_KETO]
name = "PredictMod-EHR-KETO"
version = "1.0"
data_type = "EHR"

[MDClone_Diet_Counseling]
name = "MDClone_Diet_Counseling"
version = "1.2"
data_type = "EHR"

[MDClone_Semaglutide]
name = "MDClone_Semaglutide"
version = "1.0"
data_type = "EHR"

[MDClone_Exercise]
name = "MDClone_Exercise"
version = "1.0"
data_type = "EHR"



