########### MDClone_Diet_Counseling ###############
[MDClone_Diet_Counseling]
name = "MDClone Diet Counseling"
version = "1.1"
release_date = 2023-12-01
model_type = "Decision Tree Classifier (DTC)"
data_type = "EHR Diet"
backend = "predict-backend"
condition = "Prediabetes"
intervention = "Diet - Dietary Counseling"
input_data_type = "EHR"

[MDClone_Diet_Counseling.data_meta]
Patients = 19842
"Data Features" = 19
#################################################
########### Metagenomic_Exercise ###############
[Metagenomic_Exercise]
name = "MG Exercise"
version = "1.1"
release_date = 2023-05-01
model_type = "Decision Tree Classifier (DTC)"
data_type = "Gut-Microbiome"
backend = "predict-backend"
condition = "Prediabetes"
intervention = "Exercise"
input_data_type = "Gut-Microbiome"

[Metagenomic_Exercise.data_meta]
Patients = 40
Genomes = 281
#################################################

########### Diabetes_EHR ###############
[Diabetes_EHR]
BCO = "Diabetes_EHR_v1/BCO_raw_Diabetes_EHR_Classifier.json"
model_type = "Decision Tree Classifier (DTC)"
data_type = "EHR"
backend = "predict-backend"
condition = "Prediabetes"
intervention = "Exercise"
input_data_type = "EHR-Synthea"

[Diabetes_EHR.data_meta]
#################################################

########### Epilepsy_classifier_1.1 ###############
["Epilepsy_classifier"]
BCO = "Epilepsy_microbiome_v1/BCO_raw_Epilepsy_classifier.json"
# Guessing; BCOs don't contain. Also, is this EHR, metagenomic, etc?
data_type = "Epilepsy EHR"
model_type = "Decision Tree Classifier (DTC)"
backend = "predict-backend"
condition = "Epilepsy"
intervention = "Diet - Keto Diet"
input_data_type = "Gut-Microbiome"

["Epilepsy_classifier_1.1".data_meta]
# Taken from README, BCOs should contain this in future
Patients = 500
Features = 188
#################################################
