# docker build -t karina-martinez-analysis.base -f dockerfile.base .
FROM python:3.10-slim-buster

COPY ./requirements.txt /

RUN pip3 install -r requirements.txt && \
    mkdir -p /var/log/gunicorn

# Last working code was in shap==0.44.2.dev34, 0.45.0 was "breaking"
