# docker build -t karina-martinez-analysis.base .
FROM karina-martinez-analysis.base

COPY . /backend
WORKDIR /backend

CMD ["gunicorn", "--bind", "0.0.0.0:4243", "--access-logfile", "/var/log/gunicorn/dev.log", "wsgi:app"]
# CMD ["gunicorn", "-c", "gunicorn_conf.py"]
