# docker build -t predictmod:km-analysis-backend-1.0 .
FROM predictmod:km-analysis-backend-base

COPY . /backend
WORKDIR /backend

CMD ["gunicorn", "--bind", "0.0.0.0:4243", "--access-logfile", "/var/log/gunicorn/dev.log", "wsgi:app"]
# CMD ["gunicorn", "-c", "gunicorn_conf.py"]
